# Generated by Django 6.1 on 2026-09-10 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cuit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('tipo_dato', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cuit_cuil', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.club')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad_minima', models.IntegerField()),
                ('edad_maxima', models.IntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Fichaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.categoria')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ciclo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('es_activo', models.BooleanField(default=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_test', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fichaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.fichaje')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.plantillaexamen')),
            ],
        ),
        migrations.CreateModel(
            name='MetricaRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_entero', models.IntegerField(blank=True, null=True)),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_tiempo', models.DurationField(blank=True, null=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.parametroevaluacion')),
                ('resultado_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.resultadoexamen')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('es_deportista', models.BooleanField(default=False)),
                ('es_tutor', models.BooleanField(default=False)),
                ('apto_medico', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.club')),
                ('tutor_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutelados', to='clubes.socio')),
                ('usuario_cuit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubes.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='fichaje',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.socio'),
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.club')),
                ('usuario_cuit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubes.usuario')),
            ],
        ),
    ]
