# Generated by Django 6.1 on 2026-10-07 01:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_fundacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='@Ingrese el nombre de la disciplina', max_length=100)),
                ('descripcion', models.TextField(help_text='@Ingrese la descripción de la disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Fichaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fichaje', models.DateField(help_text='@Ingrese la fecha de fichaje del socio')),
                ('is_active', models.BooleanField(default=True, help_text='@Indica si el fichaje está activo o no')),
            ],
        ),
        migrations.CreateModel(
            name='MetricaRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_entero', models.IntegerField(blank=True, help_text='@Ingrese el valor de la métrica registrada', null=True)),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=2, help_text='@Ingrese el valor de la métrica registrada', max_digits=10, null=True)),
                ('valor_tiempo', models.DurationField(blank=True, help_text='@Ingrese el valor de la métrica registrada', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='@Ingrese las observaciones de la métrica registrada', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='@Ingrese el nombre del parámetro de evaluación', max_length=100)),
                ('unidad_medida', models.CharField(help_text='@Ingrese la unidad de medida del parámetro de evaluación', max_length=200)),
                ('tipo_dato', models.CharField(help_text='@Ingrese el tipo de dato del parámetro de evaluación', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanillaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_examen', models.DateField(help_text='@Ingrese la fecha del examen')),
                ('nombre', models.CharField(help_text='@Ingrese el nombre del examen', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_test', models.DateField(help_text='@Ingrese la fecha del resultado del examen')),
                ('valor', models.CharField(help_text='@Ingrese el valor del resultado del examen', max_length=100)),
                ('observaciones', models.TextField(blank=True, help_text='@Ingrese las observaciones del resultado del examen', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(help_text='@Ingrese la fecha de nacimiento del usuario')),
                ('es_deportista', models.BooleanField(default=False, help_text='@Indica si el socio es deportista o no')),
                ('es_tutor', models.BooleanField(default=False, help_text='@Indica si el socio es tutor o no')),
                ('apto_medico', models.BooleanField(default=False, help_text='@Indica si el socio tiene apto médico o no')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='@Ingrese el nombre de la categoría', max_length=100)),
                ('descripcion', models.TextField(help_text='@Ingrese la descripción de la categoría')),
                ('edad_minima', models.IntegerField(help_text='@Ingrese la edad mínima de la categoría', validators=[django.core.validators.MinValueValidator(0)])),
                ('edad_maxima', models.IntegerField(help_text='@Ingrese la edad máxima de la categoría', validators=[django.core.validators.MinValueValidator(0)])),
                ('club_id', models.ManyToManyField(to='clubes.club')),
                ('disciplina_id', models.ManyToManyField(to='clubes.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.club')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='clubes_id',
            field=models.ManyToManyField(related_name='disciplinas', through='clubes.DisciplinaClub', to='clubes.club'),
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.IntegerField(help_text='@Ingrese la cantidad de años de experiencia del entrenador', validators=[django.core.validators.MinValueValidator(0)])),
                ('club_id', models.ManyToManyField(related_name='entrenadores', to='clubes.club')),
            ],
        ),
    ]
