# Generated by Django 6.1 on 2026-09-12 22:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(help_text='Ingrese el año del ciclo', max_length=4, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)])),
                ('fecha_inicio', models.DateField(help_text='Ingrese la fecha de inicio del ciclo', validators=[django.core.validators.MinValueValidator(2026)])),
                ('fecha_fin', models.DateField(help_text='Ingrese la fecha de fin del ciclo', validators=[django.core.validators.MaxValueValidator(2027)])),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del club', max_length=100)),
                ('direccion', models.CharField(help_text='Ingrese la dirección del club', max_length=200)),
                ('telefono', models.CharField(help_text='Ingrese el teléfono del club', max_length=15)),
                ('email', models.EmailField(help_text='Ingrese el correo electrónico del club', max_length=254)),
                ('fecha_fundacion', models.DateField(help_text='Ingrese la fecha de fundación del club')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='@Ingrese el nombre del parámetro de evaluación', max_length=100)),
                ('unidad_medida', models.CharField(help_text='@Ingrese la unidad de medida del parámetro de evaluación', max_length=200)),
                ('tipo_dato', models.CharField(help_text='@Ingrese el tipo de dato del parámetro de evaluación', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='@Ingrese el nombre de la disciplina', max_length=100)),
                ('descripcion', models.TextField(help_text='@Ingrese la descripción de la disciplina')),
                ('club_id', models.ManyToManyField(to='clubes.club')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='@Ingrese el nombre de la categoría', max_length=100)),
                ('descripcion', models.TextField(help_text='@Ingrese la descripción de la categoría')),
                ('edad_minima', models.IntegerField(help_text='@Ingrese la edad mínima de la categoría', validators=[django.core.validators.MinValueValidator(0)])),
                ('edad_maxima', models.IntegerField(help_text='@Ingrese la edad máxima de la categoría', validators=[django.core.validators.MinValueValidator(0)])),
                ('club_id', models.ManyToManyField(to='clubes.club')),
                ('disciplina_id', models.ManyToManyField(to='clubes.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.IntegerField(help_text='@Ingrese la cantidad de años de experiencia del entrenador', validators=[django.core.validators.MinValueValidator(0)])),
                ('club_id', models.ManyToManyField(to='clubes.club')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customauth.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='entrenador_id',
            field=models.ManyToManyField(to='clubes.entrenador'),
        ),
        migrations.CreateModel(
            name='Fichaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fichaje', models.DateField(help_text='@Ingrese la fecha de fichaje del socio')),
                ('is_active', models.BooleanField(default=True, help_text='@Indica si el fichaje está activo o no')),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.categoria')),
                ('ciclo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ciclo')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='PlanillaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_examen', models.DateField(help_text='@Ingrese la fecha del examen')),
                ('nombre', models.CharField(help_text='@Ingrese el nombre del examen', max_length=100)),
                ('diciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.disciplina')),
                ('fichaje_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.fichaje')),
                ('parametro_id', models.ManyToManyField(to='clubes.parametroevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_test', models.DateField(help_text='@Ingrese la fecha del resultado del examen')),
                ('valor', models.CharField(help_text='@Ingrese el valor del resultado del examen', max_length=100)),
                ('observaciones', models.TextField(blank=True, help_text='@Ingrese las observaciones del resultado del examen', null=True)),
                ('planilla_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.planillaexamen')),
            ],
        ),
        migrations.CreateModel(
            name='MetricaRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_entero', models.IntegerField(blank=True, help_text='@Ingrese el valor de la métrica registrada', null=True)),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=2, help_text='@Ingrese el valor de la métrica registrada', max_digits=10, null=True)),
                ('valor_tiempo', models.DurationField(blank=True, help_text='@Ingrese el valor de la métrica registrada', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='@Ingrese las observaciones de la métrica registrada', null=True)),
                ('parametro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.parametroevaluacion')),
                ('resultado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.resultadoexamen')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(help_text='@Ingrese la fecha de nacimiento del usuario')),
                ('es_deportista', models.BooleanField(default=False, help_text='@Indica si el socio es deportista o no')),
                ('es_tutor', models.BooleanField(default=False, help_text='@Indica si el socio es tutor o no')),
                ('apto_medico', models.BooleanField(default=False, help_text='@Indica si el socio tiene apto médico o no')),
                ('club_id', models.ManyToManyField(to='clubes.club')),
                ('tutor_responsable_id', models.ForeignKey(blank=True, help_text='@Ingrese el tutor responsable del socio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubes.socio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customauth.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='fichaje',
            name='socio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.socio'),
        ),
    ]
