# Generated by Django 6.1 on 2026-10-07 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='entrenador_id',
            field=models.ManyToManyField(related_name='disciplinas', to='clubes.entrenador'),
        ),
        migrations.AddField(
            model_name='fichaje',
            name='categoria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.categoria'),
        ),
        migrations.AddField(
            model_name='fichaje',
            name='ciclo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.ciclo'),
        ),
        migrations.AddField(
            model_name='fichaje',
            name='disciplina_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.disciplina'),
        ),
        migrations.AddField(
            model_name='metricaregistrada',
            name='parametro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.parametroevaluacion'),
        ),
        migrations.AddField(
            model_name='planillaexamen',
            name='diciplina_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.disciplina'),
        ),
        migrations.AddField(
            model_name='planillaexamen',
            name='fichaje_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.fichaje'),
        ),
        migrations.AddField(
            model_name='planillaexamen',
            name='parametro_id',
            field=models.ManyToManyField(to='clubes.parametroevaluacion'),
        ),
        migrations.AddField(
            model_name='resultadoexamen',
            name='planilla_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.planillaexamen'),
        ),
        migrations.AddField(
            model_name='metricaregistrada',
            name='resultado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.resultadoexamen'),
        ),
        migrations.AddField(
            model_name='socio',
            name='club_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.club'),
        ),
        migrations.AddField(
            model_name='socio',
            name='tutor_responsable_id',
            field=models.ForeignKey(blank=True, help_text='@Ingrese el tutor responsable del socio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubes.socio'),
        ),
        migrations.AddField(
            model_name='socio',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaje',
            name='socio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichajes', to='clubes.socio'),
        ),
        migrations.AddConstraint(
            model_name='disciplinaclub',
            constraint=models.UniqueConstraint(fields=('club_id', 'disciplina_id'), name='unique_disciplina_por_club'),
        ),
    ]
