# Generated by Django 6.1 on 2026-09-12 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='año',
            field=models.IntegerField(max_length=4, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)]),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='fecha_fin',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(2027)]),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='fecha_inicio',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(2026)]),
        ),
    ]
