# Generated by Django 6.1 on 2026-09-12 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0002_alter_ciclo_año_alter_ciclo_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='año',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)]),
        ),
    ]
