# Generated by Django 6.1 on 2026-09-12 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_alter_ciclo_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='año',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)]),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
