# Generated by Django 6.1 on 2026-09-22 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0004_alter_ciclo_año_alter_ciclo_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='club',
            name='fecha_fundacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='club_id',
            field=models.ManyToManyField(related_name='disciplinas', to='clubes.club'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='entrenador_id',
            field=models.ManyToManyField(related_name='disciplinas', to='clubes.entrenador'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='club_id',
            field=models.ManyToManyField(related_name='entrenadores', to='clubes.club'),
        ),
        migrations.RemoveField(
            model_name='socio',
            name='club_id',
        ),
        migrations.AddField(
            model_name='socio',
            name='club_id',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='clubes.club'),
            preserve_default=False,
        ),
    ]
