# Generated by Django 6.1 on 2026-09-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit_cuil', models.CharField(help_text='@Ingrese el CUIT/CUIL del usuario', max_length=11, unique=True)),
                ('nombre', models.CharField(help_text='@Ingrese el nombre del usuario', max_length=100)),
                ('apellido', models.CharField(help_text='@Ingrese el apellido del usuario', max_length=100)),
                ('email', models.EmailField(help_text='@Ingrese el correo electrónico del usuario', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='@Indica si el usuario está activo o no')),
                ('is_staff', models.BooleanField(default=False, help_text='@Indica si el usuario es staff o no')),
            ],
        ),
    ]
